[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
nodejs_version = "16" 